#!/usr/bin/env bash

case $BLOCK_BUTTON in
    1) light -A 5 ;; # left
    2) ;; # middle
    3) light -U 5 ;; # right
esac

percent=$(light)
percent=${percent%.*}

echo "${percent}%"
echo "${percent}%"
echo "#ffece0"
