#!/usr/bin/env bash

# %a = short day [Thu]
# %b = short month [Dec]
# %d = day number
# %I = 12h hours
# %M = minutes
# %p = am/pm
# date '+%a %b %d %I:%M%p'
# date '+%a %d %I:%M%p'
date '+%a %d %T'

case $BLOCK_BUTTON in
    1) pgrep -x dunst >/dev/null && notify-send "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" ;;
    2) "$TERMINAL" -e calcurse ;;
    3) pgrep -x dunst >/dev/null && notify-send "<b>📅 Time/date module:</b>
- Left click to show month via \`cal\`
- Middle click opens calcurse if installed" ;;
esac
