#!/usr/bin/env bash

# directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias ........='cd ../../../../../../..'
alias cd..='cd ..'

# some useful vim aliases becuase some times my brain is still in vim
alias :e=vim
alias :q=exit
alias :wq=exit
alias :qa=exit

# quick shortcuts to save keystorkes
alias c=cmake
alias cc=cclean
alias ct=ctest
alias cdg="cd $(git root)"
alias df="df -Tha --total"
alias g=git
alias groot='cd $(git rev-parse --show-toplevel 2> /dev/null || echo -n ".")'
[[ $SHELL =~ /zsh$  ]] && alias src='source ~/.config/zsh/.zshrc'
[[ $SHELL =~ /bash$  ]] && alias src='source ~/.bashrc'
# alias src='source ~/.bashrc'
alias e=$EDITOR
alias ep='vim -c CtrlP'
alias t=tmux
alias v=vim
alias psake='powershell -c Invoke-Psake'

# default command flags
alias pgrep='pgrep -l'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias bat='bat --terminal-width $(tput cols)'

[[ -n "$(command -v exa)" ]] && {
    alias ls="exa --group-directories-first --color=auto --git"
    alias ll="exa --group-directories-first --color=auto --git -la"
    alias l="exa --group-directories-first --color=auto --git -a"
} || {
    # ls aliases this is needed for osx as ls on mac does not have --color=always
    [[ -n $(command ls --color=auto 2>/dev/null) ]] && ls_color='--color=auto'
    alias ls="ls --group-directories-first -CFG $ls_color"
    alias ll="ls -lha $ls_color"
    alias l="ls -a $ls_color"
    unset ls_color
}

alias mirror='sudo reflector --protocol https --latest 50 --number 20 --sort rate --save /etc/pacman.d/mirrorlist'

# for python virtual environments quick way to activate and deactivate
alias vpae='[[ -d ./venv ]] && { [[ -f ./venv/Scripts/activate ]] && { source ./venv/Scripts/activate ; } || { source ./venv/bin/activate ; } }'
alias vpde='hash deactivate 7>/dev/null && deactivate'
alias vpwp='which python ; which pip'

# update the vscode list
alias update-vscode="code --list-extensions | xargs -L 1 echo code --install-extension > ~/.config/code/install-extensions.sh"

# sudo commands
[[ -n "$(command -v sudo)" ]] && {
    alias pacman="sudo pacman --color auto"
}

# shortcut edit files
alias ea="(cd ~/.config/awesome && $EDITOR rc.lua)"
alias eg="(cd ~/.config/git && $EDITOR config)"
alias ev="(cd ~/.vim && $EDITOR vimrc)"
