#!/usr/bin/env bash

# directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias ........='cd ../../../../../../..'
alias cd..='cd ..'

# some useful vim aliases becuase some times my brain is still in vim
alias :e=vim
alias :q=exit
alias :wq=exit
alias :qa=exit

# quick shortcuts to save keystorkes
alias c=cmake
alias cc=cclean
alias ct=ctest
alias df="df -Tha --total"
alias g=git
alias groot='cd $(git rev-parse --show-toplevel 2> /dev/null || echo -n ".")'
[[ $SHELL =~ /zsh$  ]] && alias src='source ~/.config/zsh/.zshrc'
[[ $SHELL =~ /bash$  ]] && alias src='source ~/.bashrc'
# alias src='source ~/.bashrc'
alias t=tmux
alias v=vim
alias vp='vim -c CtrlP'
alias psake='powershell -c psake'

# default command flags
alias pgrep='pgrep -l'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'

# ls aliases this is needed for osx as ls on mac does not have --color=always
[[ -n $(command ls --color=auto 2>/dev/null) ]] && ls_color='--color=auto'
alias ls="ls --group-directories-first -CFG $ls_color"
alias ll="ls -lha $ls_color"
alias l="ls -la $ls_color"
unset ls_color

alias pacman='sudo pacman --color auto'
alias mirror='sudo reflector --protocol https --latest 50 --number 20 --sort rate --save /etc/pacman.d/mirrorlist'

# for python virtual environments quick way to activate and deactivate
alias vpae='[[ -d ./venv ]] && { [[ -f ./venv/Scripts/activate ]] && { source ./venv/Scripts/activate ; } || { source ./venv/bin/activate ; } }'
alias vpde='hash deactivate 7>/dev/null && deactivate'
alias vpwp='which python ; which pip'

# update the vscode list
alias update-vscode="code --list-extensions | xargs -L 1 echo code --install-extension > ~/.config/code/install-extensions.sh"

# sudo commands
[[ -n $(which sudo &>/dev/null) ]] && {
    alias pacman="sudo pacman"
}

# shortcut edit files
alias eA="(cd ~/.config/awesome && $EDITOR rc.lua)"
alias edals="$EDITOR ~/.config/shell/aliases"
alias edbpr="$EDITOR ~/.bash_profile"
alias edbrc="$EDITOR ~/.bashrc"
alias edfun="$EDITOR ~/.config/shell/functions"
alias edbsp="$EDITOR ~/.config/bspwm/bspwmrc"
alias edsx="$EDITOR ~/.config/sxhkd/sxhkdrc"
alias edg="$EDITOR ~/.config/git"
alias edi="$EDITOR ~/.config/i3/config"
alias edlbin="$EDITOR ~/.local/bin"
alias edlbsh="$EDITOR ~/.local/etc/bash"
alias edlzsh="$EDITOR ~/.local/etc/zsh"
alias ednv="$EDITOR ~/.config/nvim/init.vim"
alias edpr="$EDITOR ~/.profile"
alias edrrc="$EDITOR ~/.config/ranger/rc.conf"
alias edrrf="$EDITOR ~/.config/ranger/rifle.conf"
alias edrsp="$EDITOR ~/.config/ranger/scope.sh"
alias edsc="$EDITOR ~/.scripts"
alias edv="$EDITOR ~/.vim/vimrc"
alias edzpr="$EDITOR ~/.config/zsh/.zprofile"
alias edzrc="$EDITOR ~/.config/zsh/.zshrc"
