code --install-extension ahmadawais.shades-of-purple
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension Alexey-Strakh.stackoverflow-search
code --install-extension annliu.1987
code --install-extension archipa.icl
code --install-extension belfz.search-crates-io
code --install-extension brittanychiang.halcyon-vscode
code --install-extension bungcip.better-toml
code --install-extension cheshirekow.cmake-format
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension Compulim.vscode-clock
code --install-extension danielsrothstan.uixninja-theme
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dericcain.feather
code --install-extension dullptr.envytheme
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension endorfina.roseate
code --install-extension eppz.eppz-code
code --install-extension ExodiusStudios.comment-anchors
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension fallenwood.vimL
code --install-extension file-icons.file-icons
code --install-extension formulahendry.auto-rename-tag
code --install-extension ginfuru.ginfuru-onedark-raincoat-theme
code --install-extension huizhou.githd
code --install-extension janjoerke.align-by-regex
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension josa.markdown-table-formatter
code --install-extension josef.rouge-theme
code --install-extension joshpeng.sublime-babel-vscode
code --install-extension joytrekker.rainier
code --install-extension juanmnl.vscode-theme-1984
code --install-extension kamikillerto.vscode-colorize
code --install-extension kevinkyang.auto-comment-blocks
code --install-extension lunarlimbo.banner-comments-plus
code --install-extension luqimin.tiny-light
code --install-extension mrwilford.theme-gruvball
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension NoParanoia.noparanoia
code --install-extension PeterJausovec.vscode-docker
code --install-extension philsinatra.nested-comments
code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension pnp.polacode
code --install-extension rafamel.subtle-brackets
code --install-extension RobbOwen.synthwave-vscode
code --install-extension rpinski.shebang-snippets
code --install-extension rust-lang.rust
code --install-extension Samzyre.darkiota
code --install-extension sanderledegen.angular-follow-selector
code --install-extension SanderPilon.blockalign
code --install-extension serayuzgur.crates
code --install-extension smlombardi.slime
code --install-extension stackbreak.comment-divider
code --install-extension stkb.rewrap
code --install-extension tinkertrain.theme-panda
code --install-extension tourervit.phantom
code --install-extension twxs.cmake
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wmaurer.change-case
code --install-extension yo1dog.cursor-align
