code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension Angular.ng-template
code --install-extension belfz.search-crates-io
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.path-intellisense
code --install-extension chrmarti.regex
code --install-extension codezombiech.gitignore
code --install-extension cschlosser.doxdocgen
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension ExodiusStudios.comment-anchors
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.terminal
code --install-extension huizhou.githd
code --install-extension IronLu233.vscode-color-exchange
code --install-extension janjoerke.align-by-regex
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.winteriscoming
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension kamikillerto.vscode-colorize
code --install-extension karyfoundation.comment
code --install-extension kevinkyang.auto-comment-blocks
code --install-extension kuscamara.electron
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.PowerShell
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension philsinatra.nested-comments
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension pranaygp.vscode-css-peek
code --install-extension rafamel.subtle-brackets
code --install-extension robinbentley.sass-indented
code --install-extension rpinski.shebang-snippets
code --install-extension rust-lang.rust
code --install-extension sandorengholm.csspreview
code --install-extension smlombardi.slime
code --install-extension stkb.rewrap
code --install-extension stuart.unique-window-colors
code --install-extension swyphcosmo.spellchecker
code --install-extension tinkertrain.theme-panda
code --install-extension twxs.cmake
code --install-extension undoc.undoc
code --install-extension vector-of-bool.cmake-tools
code --install-extension vincaslt.highlight-matching-tag
code --install-extension wix.vscode-import-cost
code --install-extension wmaurer.change-case
code --install-extension wmaurer.vscode-jumpy
code --install-extension xiaokangtu.codeheader
code --install-extension yo1dog.cursor-align
code --install-extension yzhang.markdown-all-in-one
