code --install-extension ahmadawais.shades-of-purple
code --install-extension alefragnani.project-manager
code --install-extension Alexey-Strakh.stackoverflow-search
code --install-extension archipa.icl
code --install-extension belfz.search-crates-io
code --install-extension bungcip.better-toml
code --install-extension cheshirekow.cmake-format
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension Compulim.vscode-clock
code --install-extension cr-jr.chronotype-vscode-themes
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ExodiusStudios.comment-anchors
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension gaearon.subliminal
code --install-extension huizhou.githd
code --install-extension IronLu233.vscode-color-exchange
code --install-extension janjoerke.align-by-regex
code --install-extension jaredkent.laserwave
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension kamikillerto.vscode-colorize
code --install-extension kevinkyang.auto-comment-blocks
code --install-extension kuscamara.electron
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension ph-hawkins.arc-plus
code --install-extension philsinatra.nested-comments
code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension pnp.polacode
code --install-extension rafamel.subtle-brackets
code --install-extension rpinski.shebang-snippets
code --install-extension rust-lang.rust
code --install-extension SanderPilon.blockalign
code --install-extension smlombardi.slime
code --install-extension stkb.rewrap
code --install-extension Sujan.code-blue
code --install-extension tinkertrain.theme-panda
code --install-extension twxs.cmake
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wmaurer.change-case
code --install-extension yo1dog.cursor-align
