#!/bin/bash

# Original source https://github.com/LukeSmithxyz/voidrice/blob/master/.scripts/i3cmds/dmenumount
#
# Gives a dmenu prompt to mount unmounted drives.
# If they're in /etc/fstab, they'll be mounted automatically.
# Otherwise, you'll be prompted to give a mountpoint from already existsing directories.
# If you input a novel directory, it will prompt you to create that directory.

pgrep -x dmenu && exit

function getmount()
{
    [ -z "$chosen" ] && exit 1

    mp="$(find $1 | dmenu -i -p "Type in mount point.")"
    [ "$mp" = "" ] && exit 1

    if [ ! -d "$mp" ]; then
        mkdiryn=$(printf "No\\nYes" | dmenu -i -p "$mp does not exist. Create it?")
        [ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
    fi
}

function mount_usb()
{
    choice="$(echo "$usbdrives" | dmenu -i -p "Mount which drive?" | awk '{print $1}')"
    sudo -A mount "$choice" && notify-send "$choice mounted." && exit 0
    getmount "/mnt /media /mount /home -maxdepth 5 -type d"
    sudo -A mount "$choice" "$mp" && notify-send "$choice mounted to $mp."
}

usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"

if [[ -z "$usbdrives" ]]; then
    echo "Usb drive detected"
else
    echo "Mountable USB drive(s)"
    mount_usb
fi
