#!/usr/bin/env bash

set -e

function main()
{
    local max=800
    local min=10
    local file=/sys/class/backlight/intel_backlight/brightness
    local current=$(cat $file)
    local new=$current

    [[ "$2" != "" ]] && val=$(echo 2*$max/100 | bc)

    [[ "$1" = "-inc" ]] && new=$((current + $val))
    [[ "$1" = "-dec" ]] && new=$((current - $val))

    [[ $new -gt $max ]] && new=$max
    [[ $new -lt $min ]] && new=$min

    printf "%.0f%%\n" $(echo "$new/$MAX*100" | bc -l)
    echo $new > $file
}

main "$@"
