#!/usr/bin/env bash

# Example:
#   prompt "Are you sure you want to shutdown?" "shutdown -h now"
[ $(echo -e "No\nYes" | dmenu -i -p "$1" -nb darkred -sb red -sf white -nf grey -fn mono) == "Yes" ] && $2
